openapi: "3.0.0"

info:
  version: 1.0.0
  title: Sberbank elvs tracker
  license:
    name: GNU

servers:
- url: https://api.elvs.fdobrotv.com

paths:
  /quotes:
    get:
      summary: List of all quotes (котировки)
      operationId: getAllQuotes
      tags:
        - Quote
      responses:
        '200':
          description: Array of quotes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quotes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an elvl
      operationId: createPets
      tags:
        - Elvl
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /elvls:
    get:
      summary: List of all elvls (energy level – лучшая цена по данному инструменту (isin))
      operationId: getAllElvls
      tags:
        - Elvl
      responses:
        '200':
          description: Array of elvls
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Elvls"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /elvls/{isin}:
    get:
      summary: Get elvl by isin
      operationId: elvl by isin
      tags:
      - Elvl
      parameters:
      - name: isin
        in: path
        description: How many items to return at one time (max 100)
        required: false
        schema:
          $ref: '#/components/schemas/Isin'
      responses:
        '200':
          description: Elvl by isin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Elvl"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Isin:
      type: string
      minLength: 12
      maxLength: 12
      pattern: '\b([A-Z]{2})((?![A-Z]{10}\b)[A-Z0-9]{10})\b'
      example: RU000A0JX0J2

    Quote:
      type: object
      required:
        - id
        - isin
        - bid
        - ask
      properties:
        id:
          type: integer
          format: int64
        isin:
          $ref: '#/components/schemas/Isin'
        bid:
          type: integer
          example: 100.2
        ask:
          type: integer
          example: 101.9

    Quotes:
      type: array
      items:
        $ref: "#/components/schemas/Quote"

    Elvl:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    Elvls:
      type: array
      items:
        $ref: "#/components/schemas/Elvl"

    Error:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string