openapi: "3.0.0"

info:
  version: 1.0.0
  title: Sberbank elvs tracker
  license:
    name: GNU

servers:
  - url: https://api.elvs.fdobrotv.com

#TODO: Put all into https://jsonapi.org/ standard
paths:
  /quotes:
    get:
      summary: List of all quotes (котировки)
      operationId: getAllQuotes
      tags:
        - Quote
      responses:
        '200':
          description: Array of quotes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quotes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a quote
      operationId: createQuote
      tags:
        - Quote
      requestBody:
        description: Body of the quote
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuoteIn'
      responses:
        '201':
          description: Created quote
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quote"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /elvls:
    get:
      summary: List of all elvls (energy level – лучшая цена по данному инструменту (isin))
      operationId: getAllElvls
      tags:
        - Elvl
      responses:
        '200':
          description: Array of elvls
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Elvls"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /elvls/{isin}:
    get:
      summary: Get elvl by isin
      operationId: getElvlByIsin
      tags:
        - Elvl
      parameters:
        - name: isin
          in: path
          description: How many items to return at one time (max 100)
          required: false
          schema:
            $ref: '#/components/schemas/Isin'
      responses:
        '200':
          description: Elvl by isin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Elvl"
        '404':
          description: Elvl not found by the isin
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Isin:
      type: string
      minLength: 12
      maxLength: 12
      pattern: '\b([A-Z]{2})((?![A-Z]{10}\b)[A-Z0-9]{10})\b'
      example: RU000A0JX0J2

    QuoteIn:
      type: object
      required:
        - isin
        - ask
      properties:
        isin:
          $ref: '#/components/schemas/Isin'
        bid:
          type: number
          example: 100.2
        ask:
          type: number
          example: 101.9

    Quote:
      allOf:
        - $ref: '#/components/schemas/QuoteIn'
        - type: object
          required:
            - id
            - elvl
          properties:
            id:
              type: string
              format: uuid
            elvl:
              type: number
              example: 100.2

    Quotes:
      type: array
      items:
        $ref: "#/components/schemas/Quote"

    Elvl:
      type: object
      required:
        - isin
        - price
      properties:
        isin:
          $ref: "#/components/schemas/Isin"
        price:
          type: number
          example: 101.9

    Elvls:
      type: array
      items:
        $ref: "#/components/schemas/Elvl"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string